apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: k-s-odoo-live-code-dev
build:
  artifacts:
    - image: odoo-live-dev
      context: src/docker/odoo
      docker:
        dockerfile: Dockerfile
    - image: postgres-letta
      context: src/docker/letta
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
