# Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-odoo-live-code-dev

# Database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-letta-pvc
  namespace: k8s-odoo-live-code-dev
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-letta
  namespace: k8s-odoo-live-code-dev
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres-letta }
  template:
    metadata:
      labels: { app: postgres-letta }
    spec:
      containers:
        - name: postgres
          image: kobrostech/postgres-letta:18.0-letta
          imagePullPolicy: IfNotPresent
          env:
            - { name: POSTGRES_DB, value: "odoo" }
            - { name: POSTGRES_USER, value: "odoo" }
            - { name: POSTGRES_PASSWORD, value: "odoo" }
          volumeMounts:
            - { name: data, mountPath: /letta-client/data }
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-letta-pvc

# Odoo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-filestore-pvc
  namespace: k8s-odoo-live-code-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: k8s-odoo-live-code-dev
spec:
  replicas: 1
  selector:
    matchLabels: { app: odoo }
  template:
    metadata:
      labels: { app: odoo }
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;",
            ]
      containers:
        - name: odoo
          image: kobrostech/odoo-live-dev:18.0-letta
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8069
          env:
            - { name: DB_HOST, value: "postgres" }
            - { name: DB_USER, value: "odoo" }
            - { name: DB_PASSWORD, value: "odoo" }
            - { name: DB_NAME, value: "odoo" }
          volumeMounts:
            - {
                name: odoo-filestore,
                mountPath: /root/.local/share/Odoo/filestore,
              }
      volumes:
        - name: odoo-filestore
          persistentVolumeClaim:
            claimName: odoo-filestore-pvc

# Creat letta DB Job
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-letta-db
  namespace: k8s-odoo-live-code-dev
spec:
  template:
    spec:
      containers:
        - name: init
          image: postgres-letta:1.0
          command: ["sh", "-c"]
          args:
            - |
              psql -h postgres -U odoo -c "CREATE DATABASE letta OWNER odoo;" &&
              psql -h postgres -U odoo -d letta -c "CREATE EXTENSION IF NOT EXISTS vector;"
          env:
            - name: PGPASSWORD
              value: "odoo"
      restartPolicy: Never

# letta server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letta-pvc
  namespace: k8s-odoo-live-code-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: letta
  namespace: k8s-odoo-live-code-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letta
  template:
    metadata:
      labels:
        app: letta
    spec:
      containers:
        - name: letta
          image: letta/letta:latest
          ports:
            - containerPort: 8283
          env:
            - {
                name: LETTA_PG_URI,
                value: postgresql://odoo:odoo@postgres:5432/letta,
              }
            - { name: SECURE, value: "true" }
            - { name: LETTA_SERVER_PASSWORD, value: "admin" }
            # - { name: OPENAI_API_KEY, value: "my-top-secret-key" }
          volumeMounts:
            - name: letta-pv
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: letta-pv
          persistentVolumeClaim:
            claimName: letta-pvc
