# Database
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: k8s-odoo-live-code-dev
spec:
  selector:
    app: postgres-letta
  ports:
    - { port: 5432, targetPort: 5432 }


# Odoo
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: k8s-odoo-live-code-dev
spec:
  type: LoadBalancer
  ports:
  - { port: 8069, targetPort: 8069 }
  selector:
    app: odoo

# letta server
---
apiVersion: v1
kind: Service
metadata:
  name: letta
  namespace: k8s-odoo-live-code-dev
spec:
  type: LoadBalancer
  selector:
    app: letta
  ports:
  - { port: 8283, targetPort: 8283 }
